### ISSUE TITLE
How to use your code? 

### ISSUE THREAD

**Issue by kaohaochuan** [adrinta/MAGNET#1]
Hello, thanks you for your great work!
Can you write a read_me file to tell me how to implement?
Maybe you can upload your thesis research?
I want to reproduce your work!

**Comment by adrinta** [comment]
i am still working on the code to reproduce this paper https://arxiv.org/abs/2003.11644. I have tried and i am sure i am on the right track but still not getting same result as paper.

**Comment by kaohaochuan** [comment]
@adrinta  I still working on it too!
I have asked original author , but he say that he won't  release the code :(
He say he has take these repositories as reference.

> [GCN](https://github.com/tkipf/gcn
> )

> Hi, our paper was inspired by [ML-GCN](https://github.com/Megvii-Nanjing/ML-GCN/)
> You can play with their code. I am quite busy to re-write and modify it according to tf2 or latest pytorch.

hope that it can help you!

**Comment by adrinta** [comment]
@lockingkao i have asked the author too and got the same answer, and i reply the email to ask several question to clarify things but he doesnt answer until now (I have wait more than a month). I recently upload the last model i have tried, you can check it out. I hope you can let me know if you have managed to reproduce it.

**Comment by kaohaochuan** [comment]
@adrinta  I have wait more than 5 month...
Okay ! Hope we can reproduce it soon!
If you have any problem , feel free to ask!
